name: "Bug report"
description: "Create a report to help us improve"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction Steps"
      description: "How did you encounter this bug?"
      placeholder: |
        1. Run `himotoki analyze "..."`
        2. Observer error "..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Python version, OS, etc."
